// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1OEL1q1s4fIjpZVGyqydw95WlN_aKZwY',
    appId: '1:627711116395:web:0cb32dc82ff124d7ec1d2e',
    messagingSenderId: '627711116395',
    projectId: 'gym-app-99a37',
    authDomain: 'gym-app-99a37.firebaseapp.com',
    storageBucket: 'gym-app-99a37.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjQyczwOo7UOId7db2Xv7mJt86Hi1RgnU',
    appId: '1:627711116395:android:78cd28b17b8b2c6eec1d2e',
    messagingSenderId: '627711116395',
    projectId: 'gym-app-99a37',
    storageBucket: 'gym-app-99a37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_3cAFIeJ1PP_Qd4OqliuM6kEH0SyuBJ0',
    appId: '1:627711116395:ios:180104cfe4c0e0eeec1d2e',
    messagingSenderId: '627711116395',
    projectId: 'gym-app-99a37',
    storageBucket: 'gym-app-99a37.firebasestorage.app',
    androidClientId: '627711116395-1b3u758kg5jacb0rlcdk9cq20ne04lo0.apps.googleusercontent.com',
    iosClientId: '627711116395-8npucvo5nouem69uek9587c4ppmevisi.apps.googleusercontent.com',
    iosBundleId: 'com.gym.gymMobileFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_3cAFIeJ1PP_Qd4OqliuM6kEH0SyuBJ0',
    appId: '1:627711116395:ios:180104cfe4c0e0eeec1d2e',
    messagingSenderId: '627711116395',
    projectId: 'gym-app-99a37',
    storageBucket: 'gym-app-99a37.firebasestorage.app',
    androidClientId: '627711116395-1b3u758kg5jacb0rlcdk9cq20ne04lo0.apps.googleusercontent.com',
    iosClientId: '627711116395-8npucvo5nouem69uek9587c4ppmevisi.apps.googleusercontent.com',
    iosBundleId: 'com.gym.gymMobileFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1OEL1q1s4fIjpZVGyqydw95WlN_aKZwY',
    appId: '1:627711116395:web:456a08c958d3a060ec1d2e',
    messagingSenderId: '627711116395',
    projectId: 'gym-app-99a37',
    authDomain: 'gym-app-99a37.firebaseapp.com',
    storageBucket: 'gym-app-99a37.firebasestorage.app',
  );
}
